### ISSUE TITLE
Great title

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/mentors-2021#2]
**writing text is important**

- bullet 1
- 2
- helpers

`print("hello world")`

can you look [at this from aaron's tutorial](https://github.com/NASA-Openscapes/lpdaac_hls_tutorial/blob/main/environment.yml#L22-L29)

**Comment by virdi** [comment]
This is a serious issue. We need to fix this.

**Comment by erinmr** [comment]
So serious @amfriesz please fix!

**Comment by erinmr** [comment]
Closing this
