### ISSUE TITLE
How do I enable participant sharing? 

### ISSUE THREAD

**Issue by amanda-tan** [NASA-Openscapes/mentors-2021#4]
Help!

**Comment by christine-e-smit** [comment]
This is my ***spectacular*** comment.

**Comment by virdi** [comment]
+1 
Our group tried to create one issue, in collaboration. However, screen sharing is not allowed in breakout rooms.

**Comment by christine-e-smit** [comment]
@amanda-tan, @virdi  - I'm tagging you. I don't know anyone else's username.

**Comment by virdi** [comment]
It looks like screen sharing is available in Zoom, but it may need to be enabled: [https://blog.zoom.us/using-zoom-breakout-rooms/](url)

**Comment by christine-e-smit** [comment]
Ooo!! I added an image:
![image](https://user-images.githubusercontent.com/14983768/117361627-47e66980-ae88-11eb-9d8b-3711b2077b5d.png)
